### ISSUE TITLE
PR CI: Add check on rebase

### ISSUE THREAD

**Issue by AlessioC31** [RIP-Comm/clementine#100]
We currently have checks (fmt, test, lint) on PR branches. It would be useful to execute the same set of checks on the "potential" new `main` branch (PR branch rebased to current main).

This is useful because the PR branch may be not rebased to the `main`, thus merging the PR could result in broken tests.

**Comment by AlessioC31** [comment]
Another option could be to disable merging the PR if it is not rebased on `main`. If we go for this we could enable some actions that automatically rebase PRs when you comment "/rebase" or something like that.

Let's use this issue to discuss :)

@guerinoni

**Comment by guerinoni** [comment]
Something simple like

```bash
command:
      - |
          before=\$(git rev-parse HEAD)
          echo "Before: \$before"
          echo Rebasing main into PR branch...
          git rebase main --message 'Automatic rebase main for PR branch'
          after=\$(git rev-parse HEAD)
          echo "After: \$after"

          [[ \$before == \$after ]] || run_test
```

**Comment by AlessioC31** [comment]
Closing since it looks like merge queues solve this problem
