### ISSUE TITLE
Implements all the headers for the `CartridgeHeader`

### ISSUE THREAD

**Issue by AlessandroGrassi99** [RIP-Comm/clementine#17]
An easy thing to do for those who are learning Rust or for those who want to start collaborating might be to implement all cartridge headers for `CartridgeHeader` in `cartridge_header.rs`.

The headers are documented [here](https://problemkaputt.de/gbatek.htm#gbacartridgeheader).

### Headers
- [x] ROM Entry Point
- [x] Nintendo Logo
- [x] Game Title
- [x] Game Code
- [x] Maker Code
- [x] Fixed value
- [x] Main unit code
- [x] Device type
- [x] Reserved Area
- [x] Software version
- [x] Complement check
- [x] Reserved Area
### Additional Multiboot Header Entries
- [x] RAM Entry Point
- [x] Boot mode
- [x] Slave ID Number
- [x] Not used
- [x] JOYBUS Entry Pt.

**Comment by FedericoBruzzone** [comment]
Can I take care of this issue?

**Comment by AlessandroGrassi99** [comment]
Sure! Don't even ask.

**Comment by gallottino** [comment]
Solved here #25
