### ISSUE TITLE
Check if cartridge checksum is correct

### ISSUE THREAD

**Issue by FedericoBruzzone** [RIP-Comm/clementine#28]
It should be in `cartridge_header.rs`. 

Specific in the function:
``` rust
fn extract_complement_check(data: &[u8]) -> [u8; 1] {
        // TODO: this issue
        data[0x0BD..=0x0BD]
            .try_into()
            .expect("extracting complement check")
    }
```

Reference [here](https://problemkaputt.de/gbatek.htm#gbacartridgeheader) at `Complement check` header

**Comment by simo498** [comment]
It should be already veryfied in the `verify_checksum` function i think

**Comment by FedericoBruzzone** [comment]
It's true.
I would call that function here to verify the checksum is correct.
I don't like that the function returns 1 even if the checksum is wrong.
