### ISSUE TITLE
Convert HEX values to BIN - Inconsistency in the format of numbers

### ISSUE THREAD

**Issue by AlessandroGrassi99** [RIP-Comm/clementine#35]
Many values are written in hexadecimal format (like `0x0B_00_00_00`), and a few others in binary format (like `0b1110_1010_0000_0000_0000_0000_0111_1111`). It would be useful to standardize all values in binary, for readability reasons.

However, I think it is better to close #33 first because it would allow the removal of many values.

**Comment by FedericoBruzzone** [comment]
I'll take this issue

**Comment by FedericoBruzzone** [comment]
Is it correct to also change the values of the `instructions` in binary?

![Immagine 2022-09-07 235402](https://user-images.githubusercontent.com/99926684/188990487-7303cc63-5a79-412f-9ffe-701f59bce9ce.png)

**Comment by simo498** [comment]
I think in many cases hexadecimal is clearer than binary and vice versa. (ie: working with addresses in hex and working with bits/bitwise ops/masks in binary

**Comment by FedericoBruzzone** [comment]
I think like you. 

But, to make all the code more readable, I would use hex in the parts as in these screenshots and bin in all other cases (also addresses). 

Let's see what others say 👍

**Comment by AlessandroGrassi99** [comment]
> Is it correct to also change the values of the instructions and conditions in binary?
> (e.g. `0x0` to `0b0000`)
> 
> from `alu_instruction.rs` file: 
> ![Immagine 2022-09-07 235402](https://user-images.githubusercontent.com/99926684/188990487-7303cc63-5a79-412f-9ffe-701f59bce9ce.png)
> 
> from `condition.rs` file:
> ![Immagine 2022-09-08 010818](https://user-images.githubusercontent.com/99926684/188998721-9a8c2890-5e31-4885-9837-639620a7be1e.png)
> 

Nope. In the case of ALU instructions are expressed in hexadecimal in the documentation. 

The main work would be to translate the masks and of the (main) instructions. So mainly where bit manipulation and control is required.

**Comment by FedericoBruzzone** [comment]
I think this issue could be closed (with #41)
