### ISSUE TITLE
Inconsistency in the variable name for opcode

### ISSUE THREAD

**Issue by AlessandroGrassi99** [RIP-Comm/clementine#70]
In the processor logic, opcode is often called `op_code` or `opcode`. We have to decide which name to use definitely, in order not to confuse, not to have two variables doing the same thing, etc.

I propose `opcode`. It is easier to write and read. It also reflects the documentation better.

**Comment by guerinoni** [comment]
For me is the same, the meaning here is operation code, then since are 2 words is more consistent `op_code`, but no blocker from my side

**Comment by FedericoBruzzone** [comment]
I think the `op_code` is better then `opcode` for the same reason that @guerinoni said.
