### ISSUE TITLE
Add condition behavior in CPSR register

### ISSUE THREAD

**Issue by gallottino** [RIP-Comm/clementine#8]
In cpsr.rs file must be added all the behavior based on the condition parameter of the OPCODE.
```
pub(crate) fn can_execute(&self, cond: Condition) -> bool {
      match cond {
          Condition::GE => self.signed() == self.overflow(),
          // TODO: complete pattern matching for every condition
          _ => todo!(),
      }
}
```
When an instruction has been decoded the ARM cpu executes it only if the flags in the CSPR match the condition. More information [here](https://problemkaputt.de/gbatek.htm#armcpuflagsconditionfieldcond)

**Comment by FedericoBruzzone** [comment]
I'll take this issue after merging my two PRs (#40 and #37) that will fix some problem.
