### ISSUE TITLE
[DOC][OnBoarding] Add instructions to run the project

### ISSUE THREAD

**Issue by omonimus1** [RIP-Comm/clementine#96]
Add in README.md instructions about how to:
- [] Install any project dependency
- [] Run the project
- [] Run any suite of testing

**Comment by guerinoni** [comment]
Now we have https://github.com/RIP-Comm/clementine/blob/main/CONTRIBUTING.md and https://github.com/RIP-Comm/clementine/blob/main/README.md :D
